-- Zone-Draft Supabase Schema
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS underwriting_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  raw_input TEXT NOT NULL,
  band_room_id TEXT,
  status TEXT DEFAULT 'PENDING',
  bbl TEXT,
  address TEXT,
  borough TEXT,
  block TEXT,
  lot TEXT,
  zonedist1 TEXT,
  lot_area_sqft FLOAT,
  lot_depth FLOAT,
  lot_frontage FLOAT,
  latitude FLOAT,
  longitude FLOAT,
  base_far FLOAT,
  uap_far FLOAT,
  max_height_ft FLOAT,
  sky_exposure_base_ft FLOAT,
  rear_yard_ft FLOAT,
  parking_required BOOLEAN,
  uap_eligible BOOLEAN,
  max_residential_sqft FLOAT,
  max_commercial_sqft FLOAT,
  envelope_json JSONB,
  hard_cost_psf FLOAT,
  hard_cost_total FLOAT,
  soft_cost_total FLOAT,
  gdc_total FLOAT,
  projected_asset_value FLOAT,
  residual_land_value FLOAT,
  comp_avg_psf FLOAT,
  comp_count INTEGER,
  report_md TEXT,
  financial_csv TEXT,
  geometry_json TEXT
);
