import type { ZoneDraftRoomSchema } from '@/types/zone-draft';

export function generateReport(ctx: ZoneDraftRoomSchema): string {
  const lot = ctx.lot_data!;
  const zoning = ctx.zoning_analysis!;
  const envelope = ctx.building_envelope!;
  const fin = ctx.financial_analysis!;

  return `# Zone-Draft Underwriting Report
## Property: ${lot.address}
**BBL:** ${lot.bbl} | **Zone:** ${lot.zonedist1} | **Lot Area:** ${lot.lot_area_sqft.toLocaleString()} sqft

---

## Zoning Analysis
- **Base FAR:** ${zoning.base_far}
- **UAP FAR Bonus:** ${zoning.uap_far} (Universal Affordability Preference, ZR 23-154)
- **Max Height:** ${zoning.max_height_ft ? zoning.max_height_ft + ' ft' : 'Sky Exposure Plane governed'}
- **Parking Required:** ${zoning.parking_required ? 'YES' : 'NO (City of Yes 2024 elimination)'}
- **Applicable Sections:** ${zoning.applicable_zr_sections.join(', ')}

${zoning.city_of_yes_notes}

---

## Building Envelope
- **Max Residential GFA:** ${envelope.max_residential_sqft.toLocaleString()} sqft
- **Floors (Base):** ${envelope.floors_standard}
- **Floors (with UAP):** ${envelope.floors_with_uap}
- **Adversarial Iterations:** ${envelope.iteration_count}

---

## Financial Underwriting
**VERDICT: ${fin.deal_verdict}**
${fin.verdict_rationale}

| Metric | Value |
|--------|-------|
| Comp Avg PSF | $${fin.comp_avg_psf.toFixed(0)} |
| Projected Asset Value | $${(fin.projected_asset_value / 1e6).toFixed(2)}M |
| Hard Costs | $${(fin.hard_cost_total / 1e6).toFixed(2)}M |
| Soft Costs | $${(fin.soft_cost_total / 1e6).toFixed(2)}M |
| **Residual Land Value** | **$${(fin.residual_land_value / 1e6).toFixed(2)}M** |

*Report generated by Zone-Draft — Band of Agents Hackathon 2026*`;
}

export function generateCSV(fin: NonNullable<ZoneDraftRoomSchema['financial_analysis']>): string {
  const rows = [
    ['Metric', 'Value', 'Notes'],
    ['Comp Avg PSF', fin.comp_avg_psf.toFixed(2), `${fin.comp_count} comparable sales`],
    [
      'Net Sellable Sqft',
      (fin.projected_asset_value / fin.comp_avg_psf).toFixed(0),
      '85% efficiency applied',
    ],
    ['Projected GDV', fin.projected_asset_value.toFixed(0), 'Gross Development Value'],
    ['Hard Costs', fin.hard_cost_total.toFixed(0), '$375 PSF NYC mid-market 2025'],
    ['Soft Costs', fin.soft_cost_total.toFixed(0), '22% of hard costs'],
    ['Financing', fin.financing_cost.toFixed(0), '6% construction loan'],
    ['Developer Profit', fin.developer_profit.toFixed(0), '18% of GDV'],
    ['Total Project Cost', fin.total_project_cost.toFixed(0), 'All-in'],
    ['RESIDUAL LAND VALUE', fin.residual_land_value.toFixed(0), 'GDV - Total Project Cost'],
    ['Deal Verdict', fin.deal_verdict, fin.verdict_rationale],
  ];
  return rows.map((r) => r.map((c) => `"${c}"`).join(',')).join('\n');
}

export function generateGeometryJson(ctx: ZoneDraftRoomSchema): string {
  const lot = ctx.lot_data!;
  const envelope = ctx.building_envelope!;
  return JSON.stringify(
    {
      type: 'Feature',
      properties: {
        bbl: lot.bbl,
        address: lot.address,
        zonedist: lot.zonedist1,
        gross_floor_area: envelope.gross_floor_area,
      },
      geometry: {
        type: 'MultiPoint',
        coordinates: envelope.envelope_vertices.map((v) => [v.x, v.y, v.z]),
      },
      envelope_vertices: envelope.envelope_vertices,
      setback_planes: envelope.setback_planes,
    },
    null,
    2
  );
}
